"""Initial migration

Revision ID: 20df3a7f8524
Revises: 
Create Date: 2025-05-18 17:21:18.340599

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '20df3a7f8524'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('website_url', sa.String(length=500), nullable=False),
    sa.Column('keywords', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('current_phase', sa.String(length=50), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('workflow_data', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('messages', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('website_content_length', sa.Integer(), nullable=True),
    sa.Column('search_results', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('search_results_count', sa.Integer(), nullable=True),
    sa.Column('brand_brief', sa.Text(), nullable=True),
    sa.Column('search_analysis', sa.Text(), nullable=True),
    sa.Column('content_cluster', sa.Text(), nullable=True),
    sa.Column('article_ideas', sa.Text(), nullable=True),
    sa.Column('final_plan', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('in_progress', sa.Boolean(), nullable=True),
    sa.Column('selected_theme_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('topic_competitors_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('main_topic', sa.String(length=255), nullable=False),
    sa.Column('subtopics', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('keywords', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('result', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('top_domains', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('user_ip', sa.String(length=64), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('themes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('keywords', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('is_selected', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('themes')
    op.drop_table('topic_competitors_jobs')
    op.drop_table('jobs')
    # ### end Alembic commands ###
